server:
  port: 8080

spring:
  application:
    name: springboot-template

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/template_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html